// <auto-generated />
using System;
using AHPDecisionMaker.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AHPDecisionMaker.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Alternative", b =>
                {
                    b.Property<int>("AlternativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlternativeId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("AlternativeId");

                    b.HasIndex("ModelId");

                    b.ToTable("Alternatives");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.AlternativePairwiseComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlternativeAId")
                        .HasColumnType("int");

                    b.Property<int>("AlternativeBId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeAId");

                    b.HasIndex("AlternativeBId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("ModelId");

                    b.ToTable("AlternativeComparisons");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.CriteriaPairwiseComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CriterionAId")
                        .HasColumnType("int");

                    b.Property<int>("CriterionBId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CriterionAId");

                    b.HasIndex("CriterionBId");

                    b.HasIndex("ModelId");

                    b.ToTable("CriteriaComparisons");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("CriterionId");

                    b.HasIndex("ModelId");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.DecisionModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<string>("Goal")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ModelId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("DecisionModels");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Alternative", b =>
                {
                    b.HasOne("AHPDecisionMaker.Web.Entities.DecisionModel", "Model")
                        .WithMany("Alternatives")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.AlternativePairwiseComparison", b =>
                {
                    b.HasOne("AHPDecisionMaker.Web.Entities.Alternative", "AlternativeA")
                        .WithMany()
                        .HasForeignKey("AlternativeAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AHPDecisionMaker.Web.Entities.Alternative", "AlternativeB")
                        .WithMany()
                        .HasForeignKey("AlternativeBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AHPDecisionMaker.Web.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AHPDecisionMaker.Web.Entities.DecisionModel", "Model")
                        .WithMany("AlternativeComparisons")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativeA");

                    b.Navigation("AlternativeB");

                    b.Navigation("Criterion");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.CriteriaPairwiseComparison", b =>
                {
                    b.HasOne("AHPDecisionMaker.Web.Entities.Criterion", "CriterionA")
                        .WithMany()
                        .HasForeignKey("CriterionAId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AHPDecisionMaker.Web.Entities.Criterion", "CriterionB")
                        .WithMany()
                        .HasForeignKey("CriterionBId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AHPDecisionMaker.Web.Entities.DecisionModel", "Model")
                        .WithMany("CriteriaComparisons")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriterionA");

                    b.Navigation("CriterionB");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Criterion", b =>
                {
                    b.HasOne("AHPDecisionMaker.Web.Entities.DecisionModel", "Model")
                        .WithMany("Criteria")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.DecisionModel", b =>
                {
                    b.HasOne("AHPDecisionMaker.Web.Entities.Project", "Project")
                        .WithOne("DecisionModel")
                        .HasForeignKey("AHPDecisionMaker.Web.Entities.DecisionModel", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.DecisionModel", b =>
                {
                    b.Navigation("AlternativeComparisons");

                    b.Navigation("Alternatives");

                    b.Navigation("Criteria");

                    b.Navigation("CriteriaComparisons");
                });

            modelBuilder.Entity("AHPDecisionMaker.Web.Entities.Project", b =>
                {
                    b.Navigation("DecisionModel");
                });
#pragma warning restore 612, 618
        }
    }
}
